language: java
jdk:
  - openjdk8
dist: trusty
env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest
before_install:
  - chmod +x resources/geckodriver.exe
  - chmod +x resources/geckodriver
#  - mozilla-firefox-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
sudo: true
notifications:
  email: false